env:
  obs_space_keys: ["pov", "arm"]
  frame_skip: 4
  frame_stack: 4
buffer:
  cpp: True
  size: 100000
neural_network: "DuelingDQN_pov_arm"
learner:
  update_target_nn_mod: 2000
  gamma: 0.99
  learning_rate: 0.0001
  log_freq: 100
  n_step: 10
actors:
  num: 8
  rollout_size: 50
  gamma: 0.99
  n_step: 10
train:
  max_eps: 1000
  replay_start_size: 2000
  batch_size: 64
  sync_nn_mod: 100
  number_of_batchs: 16