gpu: 1
base: td3
env:
  obs_space_keys: ["cube", "arm"]
buffer:
  size: 1000000
neural_network:
  build_critic: "Critic_uni"
  build_actor:
    name: "Actor_uni"
    noisy_head: True
learner:
  polyak: 0.001
  learning_rate: 0.0001
  actor_lr: 0.0001
  log_freq: 1000
  noise_sigma: 0.0
  noise_clip: 0.056
  delay: 2
exploration: [0.0, 0.1]
actors:
  num: 16
  rollout_size: 70
  noise_sigma: 0.0
  noise_clip: 0.056
train:
  max_eps: 12000
  replay_start_size: 10000
  batch_size: 256
  sync_nn_mod: 100
  number_of_batchs: 16