gpu: 1
base: dqn
env:
  obs_space_keys: ["cube", "arm"]
buffer:
  size: 1000000
neural_network:
  build_model: "DuelingDQN_arm_cube"
learner:
  update_target_nn_mod: 2500
  gamma: 0.99
  learning_rate: 0.0001
  log_freq: 1000
actors:
  num: 16
  rollout_size: 100
  gamma: 0.99
  n_step: 10
train:
  max_eps: 12000
  replay_start_size: 50000
  batch_size: 256
  sync_nn_mod: 100
  number_of_batchs: 16