gpu: 1
base: td3
env:
  obs_space_keys: ["cube", "arm"]
buffer:
  size: 1000000
neural_network:
  build_critic: "Critic_uni"
  build_actor: "Actor_uni"
learner:
  polyak: 0.001
  learning_rate: 0.0001
  actor_lr: 0.0001
  actor_reg: 1e-5
  log_freq: 1000
  noise_sigma: 0.01
  noise_clip: 0.056
  delay: 4
exploration: [0.05, 0.25]
actors:
  num: 32
  rollout_size: 70
  noise_sigma: 0.01
  noise_clip: 0.056
train:
  max_eps: 3000
  replay_start_size: 10000
  batch_size: 256
  sync_nn_mod: 100
  number_of_batchs: 16