env:
  obs_space_keys: ["pov", "angles"]
  frame_skip: 4
  frame_stack: 4
buffer:
  size: 100000
neural_network:
  critic: "Critic_pov_angle"
  actor: "Actor_pov_angle"
agent:
  train_freq: 100
  train_quantity: 100
  log_freq: 50
  polyak: 0.99
  batch_size: 32
  replay_start_size: 500
  gamma: 0.99
  learning_rate: 0.0001
  n_step: 10
train:
  log_dir: "train/"
  episodes: 200