gpu: 1
env:
  obs_space_keys: ["cube", "arm"]
buffer:
  size: 100000
neural_network:
  critic: "Critic_uni"
  actor: "Actor_uni"
agent:
  train_freq: 100
  train_quantity: 100
  log_freq: 50
  polyak: 0.005
  batch_size: 32
  replay_start_size: 1000
  gamma: 0.99
  learning_rate: 0.0001
  n_step: 10
train:
  log_dir: "train/"
  episodes: 200