gpu: 1
env:
  obs_space_keys: ["cube", "arm"]
buffer:
  size: 100000
neural_network:
  build_model: "DuelingDQN_arm_cube"
agent:
  update_target_nn_mod: 1000
train:
  log_dir: "train/"
  episodes: 1000