gpu: 1
env:
  obs_space_keys: ["cube", "arm"]
  frame_skip: 4
  frame_stack: 4
buffer:
  size: 100000
neural_network: "DuelingDQN_arm_cube"
agent:
  update_target_nn_mod: 1000
train:
  log_dir: "train/"
  episodes: 1000