gpu: 0
base: TwinDelayedDDPG
num_actors: 8
alg_args:
  polyak: 0.001
  learning_rate: 0.0001
  actor_lr: 0.0001
  log_freq: 1000
  noise_sigma: 0.005
  noise_clip: 0.01
  delay: 2
  action_reg: [1., 1., 1., 1., 1., 1., 0.]
env:
  discretize: False
  env_kwargs:
    obs_space_keys: ["cube", "arm"]
    pose_sigma: 5
  exploration_kwargs:
    sigma_epsilon: [0.01, 0.2]
buffer:
  size: 100000
  cpp: True
neural_network:
  build_critic:
    name: "Critic_uni"
    reg: 0.0000001
  build_actor:
    name: "Actor_uni"
    reg: 0.0000001
actor_resource:
  num_gpus: 0
train:
  rollout_size: 70
  max_eps: 50000
  replay_start_size: 10000
  batch_size: 256
  sync_nn_mod: 100
  number_of_batchs: 16