gpu: 0
base: DoubleDuelingDQN
num_actors: 8
alg_args:
  update_target_nn_mod: 2500
  gamma: 0.99
  learning_rate: 0.0001
  log_freq: 1000
env:
  env_kwargs:
    obs_space_keys: ["cube", "arm"]
    pose_sigma: 5
  exploration_kwargs:
    epsilon: 0.15
buffer:
  size: 1000000
neural_network:
  build_model: "DuelingDQN_arm_cube"
actor_resource:
  num_gpus: 0
train:
  rollout_size: 100
  max_eps: 24000
  replay_start_size: 10000
  batch_size: 256
  sync_nn_mod: 100
  number_of_batchs: 16