gpu: 1
base: DoubleDuelingDQN
num_actors: 8
alg_args:
  update_target_nn_mod: 2500
  gamma: 0.99
  learning_rate: 0.0001
  log_freq: 1000
env:
  env_kwargs:
    obs_space_keys: ["pov", "arm"]
    pose_sigma: 5
    camera_resolution: [128, 128]
    randomize: True
  exploration_kwargs:
    epsilon: 0.15
buffer:
  size: 100000
neural_network:
  build_model: "DuelingDQN_uni"
actor_resource:
  num_gpus: 0
train:
  rollout_size: 70
  max_eps: 50000
  replay_start_size: 10000
  batch_size: 64
  sync_nn_mod: 100
  number_of_batchs: 16