gpu: 0
base: DoubleDuelingDQN
alg_args:
  update_target_nn_mod: 2500
  gamma: 0.99
  learning_rate: 0.0001
  log_freq: 1000
env:
  env_kwargs:
    obs_space_keys: ["cube", "arm"]
  exploration_kwargs:
    epsilon: 0.
buffer:
  size: 1000000
neural_network:
  build_model:
    name: "DuelingDQN_arm_cube"
    noisy_head: True
train:
  num_actors: 3
  rollout_size: 100
  max_eps: 1000
  replay_start_size: 50000
  batch_size: 256
  sync_nn_mod: 100
  number_of_batchs: 16