gpu: 0
base: TwinDelayedDDPG
num_actors: 8
alg_args:
  polyak: 0.001
  learning_rate: 0.0001
  actor_lr: 0.0001
  log_freq: 1000
  noise_sigma: 0.005
  noise_clip: 0.01
  delay: 2
  action_reg: [1., 1., 1., 1., 1., 1., 0.]
env:
  discretize: False
  env_kwargs:
    obs_space_keys: ["pov", "arm"]
    pose_sigma: 5
    camera_resolution: [128, 128]
    randomize: True
  exploration_kwargs:
    sigma_epsilon: [0.01, 0.2]
buffer:
  size: 100000
  cpp: True
neural_network:
  build_critic: "Critic_uni"
  build_actor: "Actor_uni"
actor_resource:
  num_gpus: 0
train:
  rollout_size: 70
  max_eps: 100000
  replay_start_size: 10000
  batch_size: 128
  sync_nn_mod: 100
  number_of_batchs: 16