gpu: 0
base: TwinDelayedDDPG
alg_args:
  polyak: 0.001
  learning_rate: 0.0001
  actor_lr: 0.0001
  log_freq: 1000
  noise_sigma: 0.015
  noise_clip: 0.056
  delay: 2
env:
  discretize: False
  env_kwargs:
    obs_space_keys: ["cube", "arm"]
  exploration_kwargs:
    sigma_epsilon: [0.0, 0.1]
buffer:
  size: 100
neural_network:
  build_critic:
    name: "Critic_uni"
    reg: 0.0000001
  build_actor:
    name: "Actor_uni"
    noisy_head: True
    reg: 0.0000001
train:
  num_actors: 4
  rollout_size: 70
  max_eps: 20
  replay_start_size: 10000
  batch_size: 256
  sync_nn_mod: 100
  number_of_batchs: 16