base: DoubleDuelingDQN
gpu: 1
env:
  env_kwargs:
    obs_space_keys: ["pov", "arm"]
    video_path: 'weights/dqn/'
    camera_resolution: [128, 128]
    randomize: True
  exploration_kwargs:
    epsilon: 0.
buffer:
  size: 100000
neural_network:
  build_model:
    name: "DuelingDQN_uni"
pretrain_weights:
    online_path: 'weights/dqn/Online.ckpt'
    target_path: 'weights/dqn/Target.ckpt'
train:
  episodes: 3
log_dir: "train/"
agent:
  update_target_nn_mod: 1000