gpu: 0
base: TwinDelayedDDPG
env:
  discretize: False
  env_kwargs:
    obs_space_keys: ["pov", "cube", "arm"]
neural_network:
  build_critic: "Critic_uni"
  build_actor: "Actor_uni"
actor_resource:
  num_gpus: 0
generate:
  max_eps: 10
  num_actors: 2