gpu: 0
base: TwinDelayedDDPG
env:
  discretize: False
  env_kwargs:
    obs_space_keys: ["pov", "cube", "arm"]
    randomize: True
    camera_resolution: [128, 128]
neural_network:
  build_critic: "Critic_uni"
  build_actor: "Actor_uni"
actor_resource:
  num_gpus: 0
actors:
  pretrain_weights:
    online_actor_path: 'train/Online_actor.ckpt'
    online_critic_path: 'train/twin_critic.ckpt'
    target_actor_path: 'train/Target_actor.ckpt'
    target_critic_path: 'train/twin_critic_1.ckpt'
generate:
  max_eps: 1000
  num_actors: 16